// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0SXAQQdNDGJqPyOWmnmEjMYLXh2SdI5o',
    appId: '1:616700099778:web:41bc32aa5f4ffd87a1cf5b',
    messagingSenderId: '616700099778',
    projectId: 'fitness-614dc',
    authDomain: 'fitness-614dc.firebaseapp.com',
    storageBucket: 'fitness-614dc.firebasestorage.app',
    measurementId: 'G-6KRYSMQGJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAml28g-afv2NQzF9PSN26imCCjs3QkrJw',
    appId: '1:616700099778:android:ceea2b602d678c6aa1cf5b',
    messagingSenderId: '616700099778',
    projectId: 'fitness-614dc',
    storageBucket: 'fitness-614dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEamCXXjy0wjA20OxB3A3ET7xVCqeUUZM',
    appId: '1:616700099778:ios:3493ae2f365e4a0aa1cf5b',
    messagingSenderId: '616700099778',
    projectId: 'fitness-614dc',
    storageBucket: 'fitness-614dc.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
